[tool.poetry]
name = "bo-nedaber"
version = "0.1.0"
description = ""
authors = ["Noam Yorav-Raphael"]
readme = "README.md"
packages = [{include = "bo_nedaber"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.92.0"
uvicorn = "^0.20.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0.4"
pylint = "^2.16.2"
mypy = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pylint."messages control"]
disable = [
    "C", # convention warnings
]

[tool.mypy]
strict = true
files = ["*.py"]
